apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  namespace: pgstuff
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: pgstuff
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
