apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: pgstuff
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Use None to create a headless service (no load balancer)
