apiVersion: v1
kind: ConfigMap
metadata:
  name: pgb-cm
  namespace: pgstuff
data:
  pgbouncer.ini: |
    [databases]
    * = host=pg-svc port=5432 dbname=postgres user=postgres password=password

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = trust
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = session
    max_client_conn = 500
    default_pool_size = 20
    server_idle_timeout = 30
  userlist.txt: |
    "postgres" "password"
