apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-deploy
  namespace: pgstuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:v1.23.1-p3
          ports:
            - containerPort: 6432
          volumeMounts:
            - name: config-volume
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
              readOnly: true
            - name: config-volume
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: pgb-cm
