apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-svc
  namespace: pgstuff
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432
  clusterIP: None
